### ISSUE TITLE
Configurar rates de experiencia

### ISSUE THREAD

**Issue by Frondor** [xyzdevuy/S9-Beta-Issue-Tracker#2]
ANTES de usar la script de migración.

**Comment by Dumitas** [comment]
Nota: El nivel de personaje esta establecido como en Webzen 650
A lo que 150 son master y dan los puntos para el Arbol obviamente, el problema es que al llegar a 400 de recibir 5-6 millones de experiencia comenzó a dar 8k-15k de experiencia. Lo que es un 0.02% - 0.03% del nivel actual y son varios miles de mobs por 1 lvl. 

Sin embargo las quest gens dan 45 - 50 millones de experiencia las iniciales, lo que son 1 nivel por misión (50 mobs), ahora mismo estoy nivel 402 (Dumitas).

Se tendría que ajustar la experiencia del 400 al 650.

**Comment by Dumitas** [comment]
Como había mencionado anteriormente el nivel 400~650 lo pone en el personaje pero solo cuenta como nivel master y solo da puntos para el arbol y experiencia master.
Pero por algún motivo ahora me esta dando experiencia común y subiendo sobre 400 (un personaje Master) y **dando puntos para sumar**. 

A los personajes EVO2 después de nivel 400 aparece como si estuvieran recibiendo experiencia pero no suben de nivel.

**Comment by Frondor** [comment]
@ric Paso esto último a inglés y lo mandás como ticket a igcn? o tenés alguna idea por qué puede estar pasando?

**Comment by Dumitas** [comment]
Acabo de comprobar que la diferencia de nivel entre la real (la que muestra el personaje en selección) y la del juego es **139**, ese es exactamente el **nivel maestro que tenia** en el personaje BETA.
Estaba a punto de llegar a 539 (400 personaje + 139 Maestro), pero supongo que el problema se solucionaría recetando el Arbol (puntos **y nivel**) al momento de migrar. 

No se si el problema es por la migración o el sistema de niveles 400-650 para representar nivel maestro (en este ultimo caso habría que comprobar que sucede con un evo3 después del reset)

**Comment by ricardoul** [comment]
No entendi bien cual es el problema, o el arreglo, que de lvl hasta 650?
Por lo que revise en las config, el maximo nivel normal es 400, y el maximo nivel master 330.
Cuando pasas el 400 probablemente no subis el nivel normal, y arranques a subir el master, y se van sumando, por eso no da exp, por lo que pasando el 400 deberias poder resetear.

**Comment by Dumitas** [comment]
**El problema en si es que en el juego me mostraba un nivel y el personaje tenia otro.**

Era que el nivel del personaje se suma el nivel del Arbol, la solución ideal seria de algún modo no incluir el nivel del arbol en el personaje. (Como esta en S6)

**_Agrego que como mencione #8 no da casi experiencia cuando se sube el arbol lo que hace casi imposible ganar puntos._**

PD: Lo de 650 era la confusión deque antes se subían solo 150 niveles.

**Comment by Frondor** [comment]
Yo creo que el máximo está a 550 ahora, por lo menos mi personaje de ahi no se movio... y llegué matando 4 bichos locos.
Lo que preocupa es que se pueda levelear bien, y fullear el pj bien, asi sean 1000 niveles

**Comment by ricardoul** [comment]
Probablemente el bug esta de cuando migramos como decis vos, pasamos el nivel master y no deberiamos, y por eso se sumaba.
No creo que podamos cambiar esto de que el nivel master no se sume al común, eso es interno del cliente.

**Comment by Dumitas** [comment]
@Frondor Llegaste rápido porque en realidad estabas llegando a 400 (te mostraba 150+ del arbol)
Si podes entra un momento a Swamp mata un mob si te da exp es que hay mas de 150 niveles del arbol.

@ricardoul podes ver la experiencia cuando es solamente master? porque como mencione no da casi nada.

**Comment by Frondor** [comment]
Se soluciona testeando con un personaje creado a partir de la migración, y ver si contabiliza los master levels cuando pasas los 400

**Comment by Dumitas** [comment]
**Si eso ya esta probado**, en la migración anterior Franco me limpio el personaje y lo dejo 400, sin nivel master. No podía subir con mobs por la poca exp, lo hice con las quest gens y da bien los puntos y el nivel.
Lo que tendrías que ver, es después de 150 si sigue dando experiencia o te dice que has llegado al nivel máximo.

**Comment by Frondor** [comment]
Entonces está bien, porque subir todo trancado en un spot era estupido, si ahora te ves forzado a hacer misiones, y de los gens, mejor!
Alguien va a tener que testear levelear el arbol entonces

**Comment by Dumitas** [comment]
**Ya lo hice**, el problema es que las misiones que dan experiencia a nivel 400 son 2 y son de matar 2 diferentes tipos de mobs, 50 de cada uno.
Y a partir del nivel 419 (master 19) la cantidad de experiencia que dan no son suficientes para completar 1 nivel (90% del nivel) hay que matar 50 mobs mas para recibir ese 10% y asi para los próximos niveles ya que el juego no acumula experiencia para niveles siguientes. 
Y supongo que mas adelante (ej nivel master 50) se van a tener que hacer 3 o 4 misiones por nivel y así progresivamente.

Me parece que para un servidor 1200x eso seria demasiado.

**Comment by Frondor** [comment]
Según esta guía, la cual no dice nada sobre los topes de nivel y el master level, parece que la exp ahora está pensada para que lo máximo de experiencia se consiga usando pet, anillos y otros buffs: https://github.com/xyzdevuy/S9-Beta-Issue-Tracker/issues/2
Sin usar ese tipo de items, la experiencia debería ser muy poca.

En la misma guía aparecer capturas con la fórmula de buffs usada en el momento, para comparar con muuruguay

**Comment by Dumitas** [comment]
Toda la experiencia extra en Mu Online es solo de caza y a 1200x no afectaría mucho recibir 3 o 4 veces la cantidad, porque hasta cierto punto es básicamente 1 mob = 1 level.

La exp que te da en nivel maestro es de 6kk-8kk aproximadamente **1200 veces menos** de la que estaba dando hasta el nivel 400. El problema como dije, es que **no aplica el multiplicador después del 400**, si se quiere dejar por misiones se tendría que modificar la cantidad de exp que da cada una.

http://www.guiamuonline.com/tabla-de-experiencia-master-level

_Si miras experiencia necesaria, a partir del 21 pide mas de 45mill (lo que dan las misiones 45-50)
a partir del 93 serian 3 misiones por nivel, a partir del 148 4 y progresivamente._


**No se cual es la guía que mencionas.**

**Comment by Frondor** [comment]
Mal yo en pegar el link incorrecto, lo edito. No me estás entendiendo, no estoy hablando de la experiencia necesaria sino la que deben dar los mobs según los diferentes buffs y fórmulas de experiencia.

**Comment by Frondor** [comment]
## Default

BaseNormalExperience = 1.0

;-------------------------------------------------------------------------------------------------------------
;-- Master level experience multiplier, formula: BaseMasterExperience + Party Bonus + VIP Bonus
;-------------------------------------------------------------------------------------------------------------
BaseMasterExperience = 1.0

;-------------------------------------------------------------------------------------------------------------
;-- Event Experience Bonus, formula: BaseNormalExperience + EventExperience
;-------------------------------------------------------------------------------------------------------------
EventExperience = 0.0

;-------------------------------------------------------------------------------------------------------------
;-- Multiplier for Quest Reward Experience
;-------------------------------------------------------------------------------------------------------------
QuestExperience = 1.0

## Sugerencia:

BaseNormalExperience = 900.0

;-------------------------------------------------------------------------------------------------------------
;-- Master level experience multiplier, formula: BaseMasterExperience + Party Bonus + VIP Bonus
;-------------------------------------------------------------------------------------------------------------
BaseMasterExperience = 700.0

;-------------------------------------------------------------------------------------------------------------
;-- Event Experience Bonus, formula: BaseNormalExperience + EventExperience
;-------------------------------------------------------------------------------------------------------------
EventExperience = 200.0

;-------------------------------------------------------------------------------------------------------------
;-- Multiplier for Quest Reward Experience
;-------------------------------------------------------------------------------------------------------------
QuestExperience = 1200.0

**Comment by ricardoul** [comment]
Igualada la masterexperience con la basexperience
