### ISSUE TITLE
Existen items con sockets repetidas, resetearselas

### ISSUE THREAD

**Issue by Frondor** [xyzdevuy/S9-Beta-Issue-Tracker#6]
Resetear las sockets de los items que tienen repetidas, al parecer se migran tan cual y eso no está permitido, rompe el pvp.

![](http://i.imgur.com/udN4HaT.png)

**Comment by ricardoul** [comment]
Podemos enfocarnos en este punto, y chequear en más cuenta de users y demas haber que onda en que casos se  da, y si siemrpe se generan asi.
Esto tiene pinta de que son sockets vacios o alg oasi ,qeu se cambio de numero, y por eso quedaron asi

**Comment by Dumitas** [comment]
Ese items es full con los socket editados, igualmente Franco tenia los mismos socket en items full.
El item que te mostré no tenia nada y apareció así también, lo único peculiar si queres tener en cuenta es que es la misma opción siempre y no es al azar, dado que si tomas el orden en "ID" FIRE es el primer seed y el seed fire +0 es este precisamente.

No se como se maneja el ID de un seed ya colocado, pero los seed o "seed spear" siempre siguen el mismo orden Fire/Water/Ice/Wind/Lighting/Ground y las opciones +0+1+2...

En fin.. esa es el la primera de todas las opciones.

**Comment by ricardoul** [comment]
Arreglado
