### ISSUE TITLE
Evento Summon the Demons

### ISSUE THREAD

**Issue by Frondor** [xyzdevuy/S9-Beta-Issue-Tracker#7]
http://www.guiamuonline.com/invocacion/summon-the-demons

Actualmente este evento no parece funcionar como corresponde, aparecen varias criaturas a la vez, y tiran bundles de joyas que habría que desactivar por un tiempo hasta que se re-inserten las joyas en el juego.

Averiguar donde y con qué frecuencia se encuentran los goblins dorados.

Estudiar más el evento.

**Comment by Dumitas** [comment]
Hay al menos 10 Goblins dorados en cada mapa.

**Comment by LexusAoG** [comment]
Eso mismo, aproximadamente. Aparecen en cada invasion de dragones dorados por lo visto.

**Comment by Frondor** [comment]
Definitivamente esto está muy fruta, hay que normalizarlo antes de abrir el server beta al público.
@ricardoul sólo para que lo tengas en cuenta, cuando este todo pronto, volvemos a este evento y lo reconfiguramos

**Comment by ricardoul** [comment]
Saque los libros de los drop de los dorados
