### ISSUE TITLE
Nivel Maestro y Experiencia

### ISSUE THREAD

**Issue by Dumitas** [xyzdevuy/S9-Beta-Issue-Tracker#8]
- Pasado el nivel 400 la cantidad de experiencia por cazar monstruos se reduce dramáticamente, a un 0.05%.
- Subir nivel maestro también sube nivel del personaje hasta 650, solo da puntos al Árbol no al personaje.
- Es imposible subir nivel cazando, y lo único que da experiencia significativa son las quest GENS, a una nivel por quest aproximadamente, calculo que a partir del nivel 420 se necesitara mas de una quest para subir y lo peor es que al terminar un nivel la experiencia no se acumula al siguiente, lo que para el otro nivel se tendrá que hacer nuevamente dos quest (y posteriormente mucho mas)

- Solución, incrementar la experiencia del nivel 400-650

#2

**Comment by Frondor** [comment]
Ya está creado el issue referente a los niveles máximos, la discusión se hace ahí. Cuidado a no spammear por esta via por favor.
